# Inventory file example (hosts.yml):
# ---
arista_switches:
  hosts:
    campus-edge-01:
      ansible_host: 192.168.121.11
    campus-dorms-01:
      ansible_host: 192.168.121.12
    campus-library-01:
      ansible_host: 192.168.121.13
    campus-law-01:
      ansible_host: 192.168.121.14
    campus-datacenter-01:
      ansible_host: 192.168.121.15
  vars:
    ansible_user: admin
    #      ansible_password: "{{ vault_ansible_password }}"
    ansible_password: "admin"
    ansible_become_method: enable
    ansible_connection: network_cli
    ansible_network_os: eos
#frr_switches:
#    hosts:
#      isp-edge-01:
#        ansible_host: 192.168.121.10
#    vars:
#      ansible_user: admin
#      ansible_password: "{{ vault_ansible_password }}"
#      ansible_connection: network_cli
#      ansible_network_os: frr
