---
- name: Copy FRR daemons file
  copy:
    src: host_vars/daemons
    dest: /etc/frr/daemons
    backup: yes
  notify: restart frr

- name: Copy interfaces configuration
  copy:
    src: host_vars/{{inventory_hostname}}_interfaces-lab3.txt
    dest: /etc/network/interfaces
    backup: yes
  notify: reload networking

- name: Copy FRR configuration
  copy:
    src: host_vars/{{inventory_hostname}}_frr-lab3.txt
    dest: /etc/frr/frr.conf
    backup: yes
  notify: reload frr

- name: Flush Handlers, best practice
  meta: flush_handlers
